[package]
name = "tiredclub-meta"
version = "1.0.0"
edition = "2021"
publish = false
authors = [ "Alessandro De Franceschi",]

[dev-dependencies]

[dependencies.tiredclub]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.34.1"
