////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    tiredclub
    (
        cancelUnstakeFirst
        cancelUnstakeSecond
        claimRewards
        compoundRewards
        compoundRewardsToSend
        createProposal
        createProposalCouncil
        distributeRoyaltiesFirstCollection
        distributeRoyaltiesSecondCollection
        distributeTeamRewards
        distributeToTacc
        distributeToTasc
        dnsRegister
        getNumberLegendaryStakedSecondCollection
        getNumberOlympianStakedSecondCollection
        getNumberStakedFirstCollection
        getNumberStakedSecondCollection
        getNumberUnstakedFirstCollection
        getNumberUnstakedSecondCollection
        getProposalById
        getProposalByIdCouncil
        getProposals
        getProposalsCouncil
        getUserActualVotingPower
        getUserStakedFirstCollection
        getUserStakedLegendarySecondCollection
        getUserStakedOlympianSecondCollection
        getUserStakedSecondCollection
        getUserUnstakedFirstCollection
        getUserUnstakedSecondCollection
        getUserVote
        getUserVoteCouncil
        getUsersStakedFirstCollection
        getUsersStakedSecondCollection
        getVoteTotal
        getVoteTotalCouncil
        getVotedPower
        getVotedPowerCouncil
        getVotingPowerTotal
        getVotingPowerTotalCouncil
        getVotingPowers
        getVotingPowersCouncil
        migrateWallet
        minimumCompoundToSend
        setMinimumCompoundToSend
        setTaccRoyaltiesSecondCollection
        setTascRoyaltiesSecondCollection
        setTeamAddresses
        setTeamRewardsAddresses
        setTeamRoyaltiesSecondCollection
        stakeFirst
        stakeMultipleFirst
        stakeMultipleSecond
        stakeSecond
        submitCouncilProposal
        taccRoyaltiesSecondCollection
        tascRoyaltiesSecondCollection
        teamAddresses
        teamRewardsAddresses
        teamRoyaltiesSecondCollection
        totalCompoundRewards
        unstakeFirst
        unstakeSecond
        userCompoundedRewards
        userRewards
        vote
        voteCouncil
        withdrawFirst
        withdrawSecond
    )
}

elrond_wasm_node::wasm_empty_callback! {}
